### ISSUE TITLE
Feature sticky actionbuttons

### ISSUE THREAD

**Issue by fourroses666** [Deesen/modxEvo_scrollFix#1]
I just thinking of the option to let the "actionButtons" (Save / Duplicate / Delete) always stick to the top (visible). 

Something like this:
http://leafo.net/sticky-kit/
https://github.com/WeCodePixels/theia-sticky-sidebar

Don't know if you it

**Comment by Deesen** [comment]
I don´t understand. Those buttons (Save + New/Stay/Leave, Duplicate, Delete) are position:fixed to top per default so they are always visible.

**Comment by fourroses666** [comment]
Ah my bad, dunno what I was thinking, must be almost weekend :cocktail:
